<?php
function officeend_reg_lic_amend_menu() {
	//-------Registration--------------------
	//--------AD START-----------------------------
	$items['admin/regsection/view-register-factory-information'] = array(
		'title'				=>	'Online Application for Registration and grant or Renewal of License of Factories',
		'type' 				=> 	 MENU_DEFAULT_LOCAL_TASK,
		'weight' 			=> 	-10,
	 );
	$items['admin/regsection/view-register-factory-information/%/%/%/%'] = array(
		'page callback'	 	=>	'drupal_get_form',
		'page arguments'	=> 	array('caf_form_registrstion_factory_information',3,4,5,6),
		'file' 	 			=> 	'includes/caf_form_registrstion_factory_information.inc',
		'access arguments' 	=>  array('permission_for_inspector'),
		'type' 				=> 	MENU_LOCAL_TASK,
	);
	
	$items['admin/regsection/view-register-occupierinformation/%/%/%/%'] = array(
		'page callback'	 	=>	'drupal_get_form',
		'page arguments'	=> 	array('details_of_occupier_registration',3,4,5,6),
		'file' 	 			=> 	'includes/details_of_occupier_registration.inc',
		'access arguments' 	=>  array('permission_for_inspector'),
		'type' 				=> 	MENU_LOCAL_TASK,
	);
	$items['admin/regsection/view-register-ownerformation/%/%/%/%'] = array(
		'page callback'	 	=>	'drupal_get_form',
		'page arguments'	=> 	array('caf_form_owner_registration',3,4,5,6),
		'file' 	 			=> 	'includes/caf_form_owner_registration.inc',
		'access arguments' 	=>  array('permission_for_inspector'),
		'type' 				=> 	MENU_LOCAL_TASK,
	);
	$items['admin/regsection/view-register-manager-directorinfomation/%/%/%/%'] = array(
		'page callback'	 	=>	'drupal_get_form',
		'page arguments'	=> 	array('details_of_manager_registration',3,4,5,6),
		'file' 	 			=> 	'includes/details_of_manager_registration.inc',
		'access arguments' 	=>  array('permission_for_inspector'),
		'type' 				=> 	MENU_LOCAL_TASK,
	);
	$items['admin/regsection/view-register-documents/%/%/%/%'] = array(
		'page callback'	 	=>	'drupal_get_form',
		'page arguments'	=> 	array('caf_form_documents_registration',3,4,5,6),
		'file' 	 			=> 	'includes/caf_form_documents_registration.inc',
		'access arguments' 	=>  array('permission_for_inspector'),
		'type' 				=> 	MENU_LOCAL_TASK,
	);
	$items['admin/regsection/view-payments-data/%/%/%/%'] = array(
		'page callback'	 	=>	'drupal_get_form',
		'page arguments'	=> 	array('view_payment_data_details',3,4,5,6),
		'file' 	 			=> 	'includes/view_payment_data_details.inc',
		'access arguments' 	=>  array('permission_for_inspector'),
		'type' 				=> 	MENU_LOCAL_TASK,
	);
	$items['admin/regsection/obsevation_preview/%/%/%/%'] = array(
		'page callback'	 	=>	'drupal_get_form',
		'page arguments'	=> 	array('application_view_register_inspector',3,4,5,6),
		'file' 	 			=> 	'includes/application_view_register_inspector.inc',
		'access arguments' 	=>  array('permission_for_inspector'),
		'type' 				=> 	MENU_LOCAL_TASK,
	);

	//--------AD END-----------------------------
	//--------DD START-----------------------------
	$items['admin/ddregistration/view-register-factory-information-dd'] = array(
		'title'				=>	'Online Application for Registration and grant or Renewal of License of Factories',
		'type' 				=> 	 MENU_DEFAULT_LOCAL_TASK,
		'weight' 			=> 	-10,
	 );
	$items['admin/ddregistration/view-register-factory-information-dd/%/%/%/%'] = array(
		'page callback'	 	=>	'drupal_get_form',
		'page arguments'	=> 	array('caf_form_registrstion_factory_information_dd',3,4,5,6),
		'file' 	 			=> 	'includes/caf_form_registrstion_factory_information_dd.inc',
		'access arguments' 	=> 	array('permission_for_deputychief'),
		
		'type' 				=> 	MENU_LOCAL_TASK,
	);
	
	$items['admin/ddregistration/view-register-occupierinformation-dd/%/%/%/%'] = array(
		'page callback'	 	=>	'drupal_get_form',
		'page arguments'	=> 	array('details_of_occupier_registration',3,4,5,6),
		'file' 	 			=> 	'includes/details_of_occupier_registration.inc',
		'access arguments' 	=> 	array('permission_for_deputychief'),
		
		'type' 				=> 	MENU_LOCAL_TASK,
	);
	$items['admin/ddregistration/view-register-ownerformation-dd/%/%/%/%'] = array(
		'page callback'	 	=>	'drupal_get_form',
		'page arguments'	=> 	array('caf_form_owner_registration',3,4,5,6),
		'file' 	 			=> 	'includes/caf_form_owner_registration.inc',
		'access arguments' 	=> 	array('permission_for_deputychief'),
		'type' 				=> 	MENU_LOCAL_TASK,
	);
	
	$items['admin/ddregistration/view-register-documents-dd/%/%/%/%'] = array(
		'page callback'	 	=>	'drupal_get_form',
		'page arguments'	=> 	array('caf_form_documents_registration',3,4,5,6),
		'file' 	 			=> 	'includes/caf_form_documents_registration.inc',
		'access arguments' 	=> 	array('permission_for_deputychief'),
		'type' 				=> 	MENU_LOCAL_TASK,
	);
	$items['admin/ddregistration/view-payments-data-dd/%/%/%/%'] = array(
		'page callback'	 	=>	'drupal_get_form',
		'page arguments'	=> 	array('view_payment_data_details',3,4,5,6),
		'file' 	 			=> 	'includes/view_payment_data_details.inc',
		'access arguments' 	=> 	array('permission_for_deputychief'),
		'type' 				=> 	MENU_LOCAL_TASK,
	);
	$items['admin/ddregistration/obsevation-preview-dd/%/%/%/%'] = array(
		'page callback'	 	=>	'drupal_get_form',
		'page arguments'	=> 	array('application_view_register_deputychief',3,4,5,6),
		'file' 	 			=> 	'includes/application_view_register_deputychief.inc',
		'access arguments' 	=> 	array('permission_for_deputychief'),
		'type' 				=> 	MENU_LOCAL_TASK,
	);

	//--------DD END-----------------------------
	//---------------------Start JD
	//-----------------------DD END-----------------
	
	//-----------------End registration---------------------------
	return $items;	

}



